### ISSUE TITLE
cURL error: Operation timed out after 10001 milliseconds with 0 out of -1 bytes received

### ISSUE THREAD

**Issue by charles85** [ably/ably-php#62]
Hi,

Recently we keep facing this timeout error. Any guide what is the causes and how we can prevent this?

Laravel Framework version 5.2.45
ably/ably-php-laravel": "^1.0"

Laravel Log:

local.ERROR: exception 'Ably\Exceptions\AblyRequestException' with message 'cURL error: Operation timed out after 10001 milliseconds with 0 out of -1 bytes received' in /var/www/html/www-data/animategame/vendor/ably/ably-php/src/Http.php:150
Stack trace:
#0 /var/www/html/www-data/animategame/vendor/ably/ably-php/src/AblyRest.php(224): Ably\Http->request('POST', 'https://e.ably-...', Array, '{"data":"{\\"upd...')
#1 /var/www/html/www-data/animategame/vendor/ably/ably-php/src/AblyRest.php(229): Ably\AblyRest->requestWithFallback('POST', '/channels/unive...', Array, '{"data":"{\\"upd...', 3)
#2 /var/www/html/www-data/animategame/vendor/ably/ably-php/src/AblyRest.php(229): Ably\AblyRest->requestWithFallback('POST', '/channels/unive...', Array, '{"data":"{\\"upd...', 2)
#3 /var/www/html/www-data/animategame/vendor/ably/ably-php/src/AblyRest.php(229): Ably\AblyRest->requestWithFallback('POST', '/channels/unive...', Array, '{"data":"{\\"upd...', 1)
#4 /var/www/html/www-data/animategame/vendor/ably/ably-php/src/AblyRest.php(143): Ably\AblyRest->requestWithFallback('POST', '/channels/unive...', Array, '{"data":"{\\"upd...')
#5 /var/www/html/www-data/animategame/vendor/ably/ably-php/src/AblyRest.php(114): Ably\AblyRest->requestInternal('POST', '/channels/unive...', Array, '{"data":"{\\"upd...', false, true)
#6 /var/www/html/www-data/animategame/vendor/ably/ably-php/src/Channel.php(104): Ably\AblyRest->post('/channels/unive...', Array, '{"data":"{\\"upd...')
#7 /var/www/html/www-data/animategame/app/Http/Controllers/Admin/GameController.php(794): Ably\Channel->publish('update-market', Array)
#8 /var/www/html/www-data/animategame/vendor/laravel/framework/src/Illuminate/Database/Connection.php(543): App\Http\Controllers\Admin\GameController->App\Http\Controllers\Admin\{closure}(Object(Illuminate\Database\MySqlConnection))
#9 [internal function]: Illuminate\Database\Connection->transaction(Object(Closure))
#10 /var/www/html/www-data/animategame/bootstrap/cache/compiled.php(11804): call_user_func_array(Array, Array)
#11 /var/www/html/www-data/animategame/bootstrap/cache/compiled.php(6325): Illuminate\Database\DatabaseManager->__call('transaction', Array)
#12 /var/www/html/www-data/animategame/bootstrap/cache/compiled.php(6325): Illuminate\Database\DatabaseManager->transaction(Object(Closure))
#13 /var/www/html/www-data/animategame/app/Http/Controllers/Admin/GameController.php(800): Illuminate\Support\Facades\Facade::__callStatic('transaction', Array)
#14 /var/www/html/www-data/animategame/app/Http/Controllers/Admin/GameController.php(800): Illuminate\Support\Facades\DB::transaction(Object(Closure))
#15 [internal function]: App\Http\Controllers\Admin\GameController->ajaxUpdateUniversalAllManualOddMatch()
#16 /var/www/html/www-data/animategame/bootstrap/cache/compiled.php(9424): call_user_func_array(Array, Array)
#17 /var/www/html/www-data/animategame/bootstrap/cache/compiled.php(9486): Illuminate\Routing\Controller->callAction('ajaxUpdateUnive...', Array)
#18 /var/www/html/www-data/animategame/bootstrap/cache/compiled.php(9466): Illuminate\Routing\ControllerDispatcher->call(Object(App\Http\Controllers\Admin\GameController), Object(Illuminate\Routing\Route), 'ajaxUpdateUnive...')
#19 [internal function]: Illuminate\Routing\ControllerDispatcher->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#20 /var/www/html/www-data/animategame/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(52): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#21 [internal function]: Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#22 /var/www/html/www-data/animategame/bootstrap/cache/compiled.php(9948): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#23 /var/www/html/www-data/animategame/bootstrap/cache/compiled.php(9467): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#24 /var/www/html/www-data/animategame/bootstrap/cache/compiled.php(9454): Illuminate\Routing\ControllerDispatcher->callWithinStack(Object(App\Http\Controllers\Admin\GameController), Object(Illuminate\Routing\Route), Object(Illuminate\Http\Request), 'ajaxUpdateUnive...')
#25 /var/www/html/www-data/animategame/bootstrap/cache/compiled.php(8524): Illuminate\Routing\ControllerDispatcher->dispatch(Object(Illuminate\Routing\Route), Object(Illuminate\Http\Request), 'App\\Http\\Contro...', 'ajaxUpdateUnive...')
#26 /var/www/html/www-data/animategame/bootstrap/cache/compiled.php(8511): Illuminate\Routing\Route->runController(Object(Illuminate\Http\Request))
#27 /var/www/html/www-data/animategame/bootstrap/cache/compiled.php(8225): Illuminate\Routing\Route->run(Object(Illuminate\Http\Request))
#28 [internal function]: Illuminate\Routing\Router->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#29 /var/www/html/www-data/animategame/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(52): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#30 /var/www/html/www-data/animategame/bootstrap/cache/compiled.php(13474): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#31 [internal function]: Illuminate\View\Middleware\ShareErrorsFromSession->handle(Object(Illuminate\Http\Request), Object(Closure))
#32 /var/www/html/www-data/animategame/bootstrap/cache/compiled.php(9963): call_user_func_array(Array, Array)
#33 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#34 /var/www/html/www-data/animategame/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(32): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#35 /var/www/html/www-data/animategame/bootstrap/cache/compiled.php(11964): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#36 [internal function]: Illuminate\Session\Middleware\StartSession->handle(Object(Illuminate\Http\Request), Object(Closure))
#37 /var/www/html/www-data/animategame/bootstrap/cache/compiled.php(9963): call_user_func_array(Array, Array)
#38 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#39 /var/www/html/www-data/animategame/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(32): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#40 /var/www/html/www-data/animategame/bootstrap/cache/compiled.php(13213): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#41 [internal function]: Illuminate\Cookie\Middleware\AddQueuedCookiesToResponse->handle(Object(Illuminate\Http\Request), Object(Closure))
#42 /var/www/html/www-data/animategame/bootstrap/cache/compiled.php(9963): call_user_func_array(Array, Array)
#43 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#44 /var/www/html/www-data/animategame/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(32): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#45 /var/www/html/www-data/animategame/bootstrap/cache/compiled.php(13150): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#46 [internal function]: Illuminate\Cookie\Middleware\EncryptCookies->handle(Object(Illuminate\Http\Request), Object(Closure))
#47 /var/www/html/www-data/animategame/bootstrap/cache/compiled.php(9963): call_user_func_array(Array, Array)
#48 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#49 /var/www/html/www-data/animategame/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(32): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#50 [internal function]: Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#51 /var/www/html/www-data/animategame/bootstrap/cache/compiled.php(9948): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#52 /var/www/html/www-data/animategame/bootstrap/cache/compiled.php(8226): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#53 /var/www/html/www-data/animategame/bootstrap/cache/compiled.php(8217): Illuminate\Routing\Router->runRouteWithinStack(Object(Illuminate\Routing\Route), Object(Illuminate\Http\Request))
#54 /var/www/html/www-data/animategame/bootstrap/cache/compiled.php(8207): Illuminate\Routing\Router->dispatchToRoute(Object(Illuminate\Http\Request))
#55 /var/www/html/www-data/animategame/bootstrap/cache/compiled.php(2419): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#56 [internal function]: Illuminate\Foundation\Http\Kernel->Illuminate\Foundation\Http\{closure}(Object(Illuminate\Http\Request))
#57 /var/www/html/www-data/animategame/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(52): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#58 /var/www/html/www-data/animategame/bootstrap/cache/compiled.php(3286): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#59 [internal function]: Illuminate\Foundation\Http\Middleware\CheckForMaintenanceMode->handle(Object(Illuminate\Http\Request), Object(Closure))
#60 /var/www/html/www-data/animategame/bootstrap/cache/compiled.php(9963): call_user_func_array(Array, Array)
#61 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#62 /var/www/html/www-data/animategame/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(32): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#63 [internal function]: Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#64 /var/www/html/www-data/animategame/bootstrap/cache/compiled.php(9948): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#65 /var/www/html/www-data/animategame/bootstrap/cache/compiled.php(2366): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#66 /var/www/html/www-data/animategame/bootstrap/cache/compiled.php(2350): Illuminate\Foundation\Http\Kernel->sendRequestThroughRouter(Object(Illuminate\Http\Request))
#67 /var/www/html/www-data/animategame/public/index.php(54): Illuminate\Foundation\Http\Kernel->handle(Object(Illuminate\Http\Request))
#68 {main}

**Comment by charles85** [comment]
I would like to request to close this issue as apparently it was causes by Ably service downtime.
